sudo: required
services:
  - docker
branches:
  only:
  - master
  - /^greenkeeper\//
  - /^[0-9]+\.[0-9]+$/
  - code-coverage
notifications:
  slack:
    secure: DzxZ8DNGFANLnls0j0/hiKjwg6aO/gI3UO8SiRKjqCO/x27uvBCJiDkTqCx834XVzuDBp6LIdHbyUuwRFyaVHyFYTbA0pqE4fe4/DxkK5DuRDj89cw8JgoK7/g9m/J9Y6GvwaOaE4SW0tnHeTwNDVCt7/w8rn1kxDo/tWtS+3cg=
before_install:
  - docker build -t pltest .
script:
  - 'if [[ "$TRAVIS_PULL_REQUEST" != "false" && ! ( "$TRAVIS_BRANCH" =~ ^greenkeeper/ ) && ! ( "$TRAVIS_PULL_REQUEST_BRANCH" =~ ^greenkeeper/ ) ]]; then sh ./tools/verify-changelog.sh; fi'
  - docker run -itd --name=test_container pltest /bin/bash
  - docker exec -it test_container /PrairieLearn/docker/lint_js.sh
  - docker exec -it test_container /PrairieLearn/docker/lint_python.sh
  - docker exec -it test_container /PrairieLearn/docker/test_js.sh
  - docker exec -it test_container /PrairieLearn/docker/test_python.sh
after_success:
  - >
    docker exec
    -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST -e TRAVIS_BRANCH=$TRAVIS_BRANCH
    -it test_container
    /PrairieLearn/docker/coveralls.sh
# https://docs.travis-ci.com/user/coveralls/#Using-Coveralls-with-Docker-builds
# https://github.com/nickmerwin/node-coveralls/blob/b9032a18bd8d7fba7eaa0924a77e810ec4d0935a/lib/getOptions.js#L20
