services:
  pl:
    build:
      context: .
    image: prairielearn/prairielearn:local
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/pl_ag_jobs:/jobs
      - .:/PrairieLearn
    container_name: pl
    environment:
      - HOST_JOBS_DIR=${HOME}/pl_ag_jobs
      - DEV=true
    # This must be changed if you've changed Docker's address pools.
    # i.e., "default-address-pools" in /etc/docker/daemon.json
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
