name: 'Pull Request Labeler'
on:
  - pull_request

jobs:
  labeler:
    name: 'Tag PRs by code changes'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          sync-labels: true
  # labeler cannot label PRs by title: https://github.com/actions/labeler/issues/55
  title_labeler:
    name: 'Tag PRs by title'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@d4c99ad0944a95de5eff2ca226d681dcfd72e6e9 # v4
        with:
          config-path: .github/title-labeler.yml
